server:
  port: 8761
eureka:
  client:
    register-with-eureka: false   #是否将自己注册到 Eureka Server 默认为true
    fetch-registry: false       #是否从 Eureka Server 获取注册信息, 默认为 true
    service-url:
      defaultZone: http://discovery:8761/eureka/ #设置与 Eureka Server 交互的地址, 多个地址可用 , 隔开