server:
  port: 8002

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
spring:
  application:
    name: microserver-consume-movie
  security:
    user:
      name: user
      password: password
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

user:
  url: http://localhost:8035
