server:
  port: 8040
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/
turbine:
  app-config: microservice-consume-movie
  cluster-name-expression: "'default'"
