spring:
  application:
    name: microserver-discory-eureka-ha
---

spring:
  #指定profiles 为peer1
  profiles: peer1
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/ #设置与 Eureka Server 交互的地址, 多个地址可用 , 隔开
  instance:
    hostname: peer1
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #设置与 Eureka Server 交互的地址, 多个地址可用 , 隔开