server:
  port: 8035
  servlet:
    context-path: /
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  application:
    name: microserver-provider-user

mybatis:
  type-aliases-package: com.hand.*.domain
  mapper-locations: classpath:com/hand/microserversimpleprovideruser/mapper/*.xml

logging:
  level:
    root: INFO
    org.mybatis: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true